# Generated by Django 5.0.6 on 2024-07-03 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MusicianDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(max_length=100)),
                ('Last_name', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254)),
                ('Phone_No', models.CharField(max_length=100)),
                ('favo_instrument', models.CharField(choices=[('d', 'drum'), ('p', 'pianno'), ('h', 'harmony')], max_length=10)),
            ],
        ),
    ]
