# Generated by Django 5.0.6 on 2024-07-04 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musician', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musiciandetails',
            name='favo_instrument',
            field=models.CharField(choices=[('drum', 'drum'), ('pianno', 'pianno'), ('harmony', 'harmony')], max_length=10),
        ),
    ]
