# Generated by Django 5.0.6 on 2024-07-03 06:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelpractise',
            name='id',
        ),
        migrations.AddField(
            model_name='modelpractise',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='modelpractise',
            name='date_time_field',
            field=models.DateTimeField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='modelpractise',
            name='fathers_name',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='modelpractise',
            name='roll',
            field=models.IntegerField(default=None, primary_key=True, serialize=False),
        ),
    ]
