# Generated by Django 5.0.6 on 2024-07-03 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_remove_modelpractise_id_modelpractise_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelpractise',
            name='date_time_field',
            field=models.DateTimeField(default=None),
        ),
    ]
