# Generated by Django 5.0.6 on 2024-07-03 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0003_alter_modelpractise_date_time_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelpractise',
            name='email',
            field=models.EmailField(default='email@g.com', max_length=254),
        ),
    ]
